In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge,Lasso,ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error as mse
from sklearn.preprocessing import PolynomialFeatures

In [2]:
boston=pd.read_csv("Boston.csv")

In [3]:
train,test=train_test_split(boston,test_size=0.3,random_state=24)  

In [4]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
X_train=train.drop('medv',axis=1)
y_train=train['medv']
X_test=test.drop('medv',axis=1)
y_test=test['medv']

In [6]:
ridge=Ridge(alpha=0.5)
ridge.fit(X_train,y_train)
ridge.coef_

array([-0.05402282,  0.03817267, -0.02582842,  2.88819539, -8.89305927,
        4.30746508, -0.01209986, -1.34263626,  0.22942427, -0.01205126,
       -0.8045876 ,  0.01077158, -0.51463194])

In [7]:
y_pred_ridge=ridge.predict(X_test)


In [8]:
y_pred_ridge

array([22.25545238, 18.41899806, 25.65843125, 20.71879156, 21.11640533,
       34.30294251, 22.33166268, 16.25722945,  9.37247128, 29.6193513 ,
       23.03477694, 18.53575189, 15.76612963, 26.83150245, 22.33680783,
       22.86328015, 28.51476438, 31.81686069, 32.8665442 , 25.84305109,
       17.83341122, 26.26239488, 11.29775065, 23.41442826, 21.17581925,
       22.28623267, 30.54377461, 30.22189099, 16.51078348, 22.96250488,
       27.41931099, 24.52594166, 28.33867606, 18.44757863,  9.80045249,
       26.69050149, 11.51989154, 20.60382954, 38.78781196, 23.19693155,
       21.50679247, 31.02778013, 20.44796597, 17.59256487, 31.83541392,
        9.04016775, 19.01981002, 24.71228455, 23.51249327, 21.79882635,
       25.56986323, 30.90391195, 41.60778664, 16.50443709, 26.92652642,
       28.9913658 , 21.87436141, 20.26522651, 25.45069273, 12.50636593,
       17.86642932, 15.42932496, 23.19336327, 13.74828822, 23.35322026,
       11.19916621, 25.68032527, 18.76854225, 17.46517154,  6.39

In [10]:
mse(y_test,y_pred_ridge)

21.12931518037373

In [12]:
listnum=[0.1,0.5,1,2,2.5,3]
errors=[]
for i in listnum:
    ridge=Ridge(alpha=i)
    ridge.fit(X_train,y_train)
    y_pred_ridge=ridge.predict(X_test)
    errors.append((mse(y_test,y_pred_ridge)))
    
print("Best Score",np.min(errors))
i_min=np.argmin(errors)
print("best parameters",listnum[i_min]) 

Best Score 20.784843374997465
best parameters 0.1


In [13]:
lr=LinearRegression()

In [14]:
lr.fit(X_train,y_train)

LinearRegression()

In [15]:
lr.coef_

array([-5.84015348e-02,  3.74009981e-02, -9.18952118e-03,  2.98640550e+00,
       -1.29791828e+01,  4.27902999e+00, -8.50890017e-03, -1.39726186e+00,
        2.39477386e-01, -1.16953033e-02, -8.52512252e-01,  1.04780793e-02,
       -5.07993450e-01])

In [16]:
y_pred=lr.predict(X_test)

In [18]:
mse(y_test,y_pred)

20.670712756461047

In [19]:
dtr=DecisionTreeRegressor()

In [20]:
dtr.fit(X_train,y_train)


DecisionTreeRegressor()

In [21]:
y_pred_dt=dtr.predict(X_test)

In [22]:
mse(y_test,y_pred_dt)

23.212105263157895

In [23]:
X=boston.drop('medv',axis=1)
y=boston['medv']

In [24]:
import statsmodels.api as sm
X=sm.add_constant(X)
model=sm.OLS(y,X)
results=model.fit()
print(results.params)
print(results.summary())

const      36.459488
crim       -0.108011
zn          0.046420
indus       0.020559
chas        2.686734
nox       -17.766611
rm          3.809865
age         0.000692
dis        -1.475567
rad         0.306049
tax        -0.012335
ptratio    -0.952747
black       0.009312
lstat      -0.524758
dtype: float64
                            OLS Regression Results                            
Dep. Variable:                   medv   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Wed, 01 Nov 2023   Prob (F-statistic):          6.72e-135
Time:                        14:54:57   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13                      

In [25]:
poly1=PolynomialFeatures(degree=1)
X_poly1=poly1.fit_transform(X)
X_poly1

array([[1.0000e+00, 1.0000e+00, 6.3200e-03, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [1.0000e+00, 1.0000e+00, 2.7310e-02, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [1.0000e+00, 1.0000e+00, 2.7290e-02, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [1.0000e+00, 1.0000e+00, 6.0760e-02, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0000e+00, 1.0000e+00, 1.0959e-01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [1.0000e+00, 1.0000e+00, 4.7410e-02, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [26]:
X_train1,X_test1,y_train1,y_test1=train_test_split(X_poly1,y,test_size=0.3,random_state=24)

In [27]:
lr1=LinearRegression()
lr1.fit(X_train1,y_train1)

LinearRegression()

In [28]:
y_pred1=lr1.predict(X_test1)

In [29]:
mse(y_test1,y_pred1)

20.670712756461075

In [30]:
poly=PolynomialFeatures(degree=2)
X_poly2=poly.fit_transform(X)
X_poly2

array([[1.00000000e+00, 1.00000000e+00, 6.32000000e-03, ...,
        1.57529610e+05, 1.97656200e+03, 2.48004000e+01],
       [1.00000000e+00, 1.00000000e+00, 2.73100000e-02, ...,
        1.57529610e+05, 3.62766600e+03, 8.35396000e+01],
       [1.00000000e+00, 1.00000000e+00, 2.72900000e-02, ...,
        1.54315409e+05, 1.58310490e+03, 1.62409000e+01],
       ...,
       [1.00000000e+00, 1.00000000e+00, 6.07600000e-02, ...,
        1.57529610e+05, 2.23851600e+03, 3.18096000e+01],
       [1.00000000e+00, 1.00000000e+00, 1.09590000e-01, ...,
        1.54802902e+05, 2.54955600e+03, 4.19904000e+01],
       [1.00000000e+00, 1.00000000e+00, 4.74100000e-02, ...,
        1.57529610e+05, 3.12757200e+03, 6.20944000e+01]])

In [31]:
X_train2,X_test2,y_train2,y_test2=train_test_split(X_poly2,y,test_size=0.3,random_state=24)
X_test2

array([[1.00000000e+00, 1.00000000e+00, 4.89822000e+00, ...,
        1.41015270e+05, 1.22419520e+03, 1.06276000e+01],
       [1.00000000e+00, 1.00000000e+00, 1.32620000e-01, ...,
        1.55275402e+05, 6.49000350e+03, 2.71260900e+02],
       [1.00000000e+00, 1.00000000e+00, 9.06500000e-02, ...,
        1.53146996e+05, 5.34179100e+03, 1.86322500e+02],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.09590000e-01, ...,
        1.54802902e+05, 2.54955600e+03, 4.19904000e+01],
       [1.00000000e+00, 1.00000000e+00, 3.41090000e-01, ...,
        1.57529610e+05, 2.42902800e+03, 3.74544000e+01],
       [1.00000000e+00, 1.00000000e+00, 2.24380000e-01, ...,
        1.57529610e+05, 5.68757700e+03, 2.05348900e+02]])

In [32]:
lr2=LinearRegression()
lr2.fit(X_train2,y_train2)

LinearRegression()

In [33]:
y_pred2=lr2.predict(X_test2)

In [35]:
mse(y_test2,y_pred2)

19.868038880304802

In [36]:
poly3=PolynomialFeatures(degree=3)
X_poly3=poly3.fit_transform(X)
X_poly3

array([[1.00000000e+00, 1.00000000e+00, 6.32000000e-03, ...,
        7.84497458e+05, 9.84327876e+03, 1.23505992e+02],
       [1.00000000e+00, 1.00000000e+00, 2.73100000e-02, ...,
        1.43982064e+06, 3.31568672e+04, 7.63551944e+02],
       [1.00000000e+00, 1.00000000e+00, 2.72900000e-02, ...,
        6.21891098e+05, 6.37991275e+03, 6.54508270e+01],
       ...,
       [1.00000000e+00, 1.00000000e+00, 6.07600000e-02, ...,
        8.88467000e+05, 1.26252302e+04, 1.79406144e+02],
       [1.00000000e+00, 1.00000000e+00, 1.09590000e-01, ...,
        1.00312281e+06, 1.65211229e+04, 2.72097792e+02],
       [1.00000000e+00, 1.00000000e+00, 4.74100000e-02, ...,
        1.24133333e+06, 2.46452674e+04, 4.89303872e+02]])

In [37]:
X_train3,X_test3,y_train3,y_test3=train_test_split(X_poly3,y,test_size=0.3,random_state=23)

In [38]:
lr3=LinearRegression()
lr3.fit(X_train3,y_train3)

LinearRegression()

In [39]:
y_pred3=lr3.predict(X_test3)

In [40]:
mse(y_test3,y_pred3)

156148.32652828

Lasso regression

In [44]:
params=[0.1,0.5,1,2,2.5,3]
errors=[]
for a in params:
    lasso = Lasso(alpha=a)
    lasso.fit(X_train,y_train)
    y_pred=lasso.predict(X_test)
    errors.append(mse(y_test,y_pred))
    
print("Best Score",np.min(errors))
i_min=np.argmin(errors)
print("Best parameter", params[i_min])

Best Score 22.417157585441924
Best parameter 0.1


In [45]:
l1_rat=[0.1,0.25,0.5,0.8,0.9]
errors=dict()

In [46]:
params=[0.1,0.5,1,2,2.5,3]
for a in params:
    for i in l1_rat:
         elastic = ElasticNet(alpha=a,l1_ratio=i)
         elastic.fit(X_train,y_train)
         y_pred_el=elastic.predict(X_test)
         errors['alpha',str(a),"L1 ratio",str(i)]=mse(y_test,y_pred)
        
         
er_pd=pd.Series(errors)
er_pd.sort_values

<bound method Series.sort_values of alpha  0.1  L1 ratio  0.1     30.00046
                      0.25    30.00046
                      0.5     30.00046
                      0.8     30.00046
                      0.9     30.00046
       0.5  L1 ratio  0.1     30.00046
                      0.25    30.00046
                      0.5     30.00046
                      0.8     30.00046
                      0.9     30.00046
       1    L1 ratio  0.1     30.00046
                      0.25    30.00046
                      0.5     30.00046
                      0.8     30.00046
                      0.9     30.00046
       2    L1 ratio  0.1     30.00046
                      0.25    30.00046
                      0.5     30.00046
                      0.8     30.00046
                      0.9     30.00046
       2.5  L1 ratio  0.1     30.00046
                      0.25    30.00046
                      0.5     30.00046
                      0.8     30.00046
                      0.9   

In [48]:
#k fold
from sklearn.model_selection import KFold,cross_val_score
X=boston.drop('medv',axis=1)
y=boston['medv']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.15,random_state=24)  
kfold=KFold(n_splits=5,shuffle=True,random_state=23)
elastic=ElasticNet(alpha=0.1,l1_ratio=0.3)
results=cross_val_score(elastic,X_train,y_train,cv=kfold,scoring='neg_mean_squared_error')
results.mean()

-24.254819141036116